### PR TITLE
Allow case insensitive patterns

### PR DESCRIPTION
**Pull request by markdalgleish**
This is achieved by introducing a pattern type, which allows a unified approach to defining advanced patterns, including transform functions and case sensitivity as options.

Please note that this is a _breaking change_ to the API for `extractParams`, but I have documented this in the readme.

### CODE REVIEW

**Comment by moroshko** [comment]
Thanks for the PR! I like the pattern type idea.

**Comment by markdalgleish** [comment]
Great! :smile: 

Would you be able to publish this to npm?

**Comment by moroshko** [comment]
Working on this, just making some minor updates :smile:

**Comment by moroshko** [comment]
Version `3.0.2` is on npm now. Enjoy, and thanks again for a great PR :+1:

**Pull request merged**
